### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by gachasta**
Upping the rollout warning message as most customer encounter this.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@gachasta : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger18** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger19** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Comment by PRMerger19** [comment]
@KumarVivek : Thanks for your contribution! The author(s) have been notified to review your proposed change. @msftman

**Pull request merged**
